name: 'compas-actions.publish'
description: 'Publish COMPAS or its plugins to PYPI'

inputs:
  token:
    description: 'the PYPI account token'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - shell: bash
      run: |
        python setup.py clean --all sdist bdist_wheel

    - shell: bash
      run: |
          twine check dist/*
          twine upload dist/* --skip-existing
      env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ inputs.token }}
