name: 'compas-actions.publish'
description: 'Publish COMPAS or its plugins to PYPI'

inputs:
  github_token:
    description: 'The Github token'
    required: true
  publish_to_pypi:
    description: 'Whether to publish to PYPI'
    required: false
    default: 'true'
  pypi_token:
    description: 'the PYPI account token'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Get Version From Tag
      id: tag_name
      run: |
        echo "current_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get Changelog Entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v2
      with:
        version: ${{ steps.tag_name.outputs.current_version }}
        path: ./CHANGELOG.md
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.changelog_reader.outputs.changes }}
        draft: false
        prerelease: false

    - shell: bash
      if: inputs.publish_to_pypi == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        python setup.py clean --all sdist bdist_wheel
        twine check dist/*
        twine upload dist/* --skip-existing
      env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ inputs.pypi_token }}
