name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  update-major-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: nowactions/update-majorver@v1

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
